
" Database Connection Strings {{{1
let g:dbext_default_profile_devPortalSecurity   = 'type=SQLSRV:integratedlogin=1:dbname=Growth_Portal_Security:srvname=NADCWDDBS01A\INS01A'
let g:dbext_default_profile_localPortalSecurity = 'type=SQLSRV:integratedlogin=1:dbname=Growth_Portal_Security:srvname=GrowthLocal'
let g:dbext_default_profile                     = 'devPortalSecurity'

" Intellisense {{{1
function! s:syntaxAtCurrentPosition()
	return synIDattr(synID(line('.'), col('.'), 0), "name")
endfunction

" Searching {{{1
set hlsearch
set incsearch
set ignorecase

" Display {{{1
set nowrap
set laststatus=2
set statusline=%<%f\ %h%m%r%=%-14.(%l,%c%V%)\ %P
set showcmd
set guifont=Lucida_Console:h08
set number
set relativenumber
syntax enable
colorscheme phil
" set cursorline   " Too slow as of Vim 7.1
" set cursorcolumn " Too slow as of Vim 7.1

" Compatibility {{{1
behave mswin
set cpoptions=aABceFs
set backspace=indent,eol,start whichwrap+=<,>,[,]
noremap <M-Space> :simalt ~<CR>
filetype plugin on

" Miscellany {{{1
set modeline
set nocp
filetype plugin on

" Indenting {{{1
set nosmartindent
set cindent
set cinkeys=0{,0},0),:,!^F,o,O,e
set tabstop=2
set softtabstop=2
set shiftwidth=2
set noexpandtab

" Folding {{{1
set foldcolumn=5
set foldmethod=marker
set foldtext=MyFoldText()
function MyFoldText()
	let line = getline(v:foldstart)
	let sub = substitute(line, '\t', '  ', 'g')
	return sub
endfunction

" Diffing {{{1
set diffopt=icase,iwhite,filler

" Favorite @-commands {{{1
let @y = 'mzggVG"*Y`z'
let @h = 'H90|'
let @l = ':let @/ = ""'
let @j = 'mz"zyGo"zpVG:s/^/''/gv:s/$/'',/$xgvJ^"*y$"zD`z@l'
let @c = ':.s/ | / \\\r\t| /g'
